//Questo file definisce l API gRPC per il servizio URL shortener
//Service name: UrlShortenerService
//RPC: CreateShortUrl, ResolveShortUrl, GetStats

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/url_shortener.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShortUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"` //URL lunga da accorciare, deve iniziare con http/https.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortUrlRequest) Reset() {
	*x = CreateShortUrlRequest{}
	mi := &file_proto_url_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortUrlRequest) ProtoMessage() {}

func (x *CreateShortUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortUrlRequest.ProtoReflect.Descriptor instead.
func (*CreateShortUrlRequest) Descriptor() ([]byte, []int) {
	return file_proto_url_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShortUrlRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type CreateShortUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,3,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` //data di creazione originale, non cambia in caso di idempotenza
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortUrlResponse) Reset() {
	*x = CreateShortUrlResponse{}
	mi := &file_proto_url_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortUrlResponse) ProtoMessage() {}

func (x *CreateShortUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortUrlResponse.ProtoReflect.Descriptor instead.
func (*CreateShortUrlResponse) Descriptor() ([]byte, []int) {
	return file_proto_url_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShortUrlResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateShortUrlResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *CreateShortUrlResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *CreateShortUrlResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ResolveShortUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` //Codice corto da risolvere
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveShortUrlRequest) Reset() {
	*x = ResolveShortUrlRequest{}
	mi := &file_proto_url_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveShortUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveShortUrlRequest) ProtoMessage() {}

func (x *ResolveShortUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveShortUrlRequest.ProtoReflect.Descriptor instead.
func (*ResolveShortUrlRequest) Descriptor() ([]byte, []int) {
	return file_proto_url_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveShortUrlRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ResolveShortUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveShortUrlResponse) Reset() {
	*x = ResolveShortUrlResponse{}
	mi := &file_proto_url_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveShortUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveShortUrlResponse) ProtoMessage() {}

func (x *ResolveShortUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveShortUrlResponse.ProtoReflect.Descriptor instead.
func (*ResolveShortUrlResponse) Descriptor() ([]byte, []int) {
	return file_proto_url_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveShortUrlResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_proto_url_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_url_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *GetStatsRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	AccessCount   int64                  `protobuf:"varint,3,opt,name=access_count,json=accessCount,proto3" json:"access_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastAccessAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_access_at,json=lastAccessAt,proto3" json:"last_access_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_proto_url_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_url_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatsResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetStatsResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *GetStatsResponse) GetAccessCount() int64 {
	if x != nil {
		return x.AccessCount
	}
	return 0
}

func (x *GetStatsResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetStatsResponse) GetLastAccessAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAccessAt
	}
	return nil
}

var File_proto_url_shortener_proto protoreflect.FileDescriptor

const file_proto_url_shortener_proto_rawDesc = "" +
	"\n" +
	"\x19proto/url_shortener.proto\x12\x0furlshortener.v1\x1a\x1fgoogle/protobuf/timestamp.proto\":\n" +
	"\x15CreateShortUrlRequest\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\"\xa7\x01\n" +
	"\x16CreateShortUrlResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x03 \x01(\tR\voriginalUrl\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\",\n" +
	"\x16ResolveShortUrlRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"<\n" +
	"\x17ResolveShortUrlResponse\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\"%\n" +
	"\x0fGetStatsRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\xe9\x01\n" +
	"\x10GetStatsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\x12!\n" +
	"\faccess_count\x18\x03 \x01(\x03R\vaccessCount\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12@\n" +
	"\x0elast_access_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\flastAccessAt2\xaf\x02\n" +
	"\x13UrlShortenerService\x12a\n" +
	"\x0eCreateShortUrl\x12&.urlshortener.v1.CreateShortUrlRequest\x1a'.urlshortener.v1.CreateShortUrlResponse\x12d\n" +
	"\x0fResolveShortUrl\x12'.urlshortener.v1.ResolveShortUrlRequest\x1a(.urlshortener.v1.ResolveShortUrlResponse\x12O\n" +
	"\bGetStats\x12 .urlshortener.v1.GetStatsRequest\x1a!.urlshortener.v1.GetStatsResponseB\x12Z\x10urlShorter/protob\x06proto3"

var (
	file_proto_url_shortener_proto_rawDescOnce sync.Once
	file_proto_url_shortener_proto_rawDescData []byte
)

func file_proto_url_shortener_proto_rawDescGZIP() []byte {
	file_proto_url_shortener_proto_rawDescOnce.Do(func() {
		file_proto_url_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_url_shortener_proto_rawDesc), len(file_proto_url_shortener_proto_rawDesc)))
	})
	return file_proto_url_shortener_proto_rawDescData
}

var file_proto_url_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_url_shortener_proto_goTypes = []any{
	(*CreateShortUrlRequest)(nil),   // 0: urlshortener.v1.CreateShortUrlRequest
	(*CreateShortUrlResponse)(nil),  // 1: urlshortener.v1.CreateShortUrlResponse
	(*ResolveShortUrlRequest)(nil),  // 2: urlshortener.v1.ResolveShortUrlRequest
	(*ResolveShortUrlResponse)(nil), // 3: urlshortener.v1.ResolveShortUrlResponse
	(*GetStatsRequest)(nil),         // 4: urlshortener.v1.GetStatsRequest
	(*GetStatsResponse)(nil),        // 5: urlshortener.v1.GetStatsResponse
	(*timestamppb.Timestamp)(nil),   // 6: google.protobuf.Timestamp
}
var file_proto_url_shortener_proto_depIdxs = []int32{
	6, // 0: urlshortener.v1.CreateShortUrlResponse.created_at:type_name -> google.protobuf.Timestamp
	6, // 1: urlshortener.v1.GetStatsResponse.created_at:type_name -> google.protobuf.Timestamp
	6, // 2: urlshortener.v1.GetStatsResponse.last_access_at:type_name -> google.protobuf.Timestamp
	0, // 3: urlshortener.v1.UrlShortenerService.CreateShortUrl:input_type -> urlshortener.v1.CreateShortUrlRequest
	2, // 4: urlshortener.v1.UrlShortenerService.ResolveShortUrl:input_type -> urlshortener.v1.ResolveShortUrlRequest
	4, // 5: urlshortener.v1.UrlShortenerService.GetStats:input_type -> urlshortener.v1.GetStatsRequest
	1, // 6: urlshortener.v1.UrlShortenerService.CreateShortUrl:output_type -> urlshortener.v1.CreateShortUrlResponse
	3, // 7: urlshortener.v1.UrlShortenerService.ResolveShortUrl:output_type -> urlshortener.v1.ResolveShortUrlResponse
	5, // 8: urlshortener.v1.UrlShortenerService.GetStats:output_type -> urlshortener.v1.GetStatsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_url_shortener_proto_init() }
func file_proto_url_shortener_proto_init() {
	if File_proto_url_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_url_shortener_proto_rawDesc), len(file_proto_url_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_url_shortener_proto_goTypes,
		DependencyIndexes: file_proto_url_shortener_proto_depIdxs,
		MessageInfos:      file_proto_url_shortener_proto_msgTypes,
	}.Build()
	File_proto_url_shortener_proto = out.File
	file_proto_url_shortener_proto_goTypes = nil
	file_proto_url_shortener_proto_depIdxs = nil
}
